/**
 * LLM Type Definitions
 * Common interfaces for LLM client interactions
 */

/**
 * Message format for LLM conversations
 */
export interface LLMMessage {
    role: 'system' | 'user' | 'assistant' | 'tool';
    content: string;
    tool_call_id?: string;
    tool_calls?: LLMToolCall[];
}

/**
 * Tool definition in LLM-compatible format
 */
export interface LLMToolDefinition {
    type: 'function';
    function: {
        name: string;
        description: string;
        parameters: Record<string, unknown>;
    };
}

/**
 * Tool call returned by LLM
 */
export interface LLMToolCall {
    id: string;
    name: string;
    arguments: Record<string, unknown>;
}

/**
 * LLM response structure
 */
export interface LLMResponse {
    content?: string;
    tool_calls?: LLMToolCall[];
    finish_reason: 'stop' | 'tool_calls' | 'length';
    usage?: {
        prompt_tokens: number;
        completion_tokens: number;
    };
}

/**
 * Accumulated token usage across multiple LLM calls within a single run phase
 */
export interface TokenAccumulator {
    prompt_tokens: number;
    completion_tokens: number;
    total_tokens: number;
    llm_calls: number;
}

/** Create a zeroed token accumulator */
export function createTokenAccumulator(): TokenAccumulator {
    return { prompt_tokens: 0, completion_tokens: 0, total_tokens: 0, llm_calls: 0 };
}

/**
 * Add a single LLMResponse.usage into an accumulator (mutates in place).
 * Increments llm_calls unconditionally; adds tokens only if usage is present.
 */
export function accumulateTokens(
    acc: TokenAccumulator,
    usage?: { prompt_tokens: number; completion_tokens: number }
): void {
    acc.llm_calls += 1;
    if (usage) {
        acc.prompt_tokens     += usage.prompt_tokens;
        acc.completion_tokens += usage.completion_tokens;
        acc.total_tokens      += usage.prompt_tokens + usage.completion_tokens;
    }
}

/**
 * Options for LLM chat calls
 */
export interface LLMChatOptions {
    tools?: LLMToolDefinition[];
    temperature?: number;
    max_tokens?: number;
    /** Ollama 0.7+ top-level think parameter. Pass false to suppress chain-of-thought
     *  at the model level — more reliable than the /no_think text directive alone. */
    think?: boolean;
}

/**
 * LLM client interface
 */
export interface LLMClient {
    chat(messages: LLMMessage[], options?: LLMChatOptions): Promise<LLMResponse>;
}

/**
 * Plan structure generated by Planner phase
 */
export interface Plan {
    goal: string;
    steps: PlanStep[];
}

/**
 * Individual step in a plan
 */
export interface PlanStep {
    id: number;
    description: string;
    tool_intent: string | null;
}
